### ISSUE TITLE
NOT CONTAINS is not working

### ISSUE THREAD

**Issue by johnowl** [johnowl/owl-rules#15]
When we use a rule like this `[1 2 3 4] NOT CONTAINS 4` , an exception is thrown.

Bug discovered using the @udhos test suite, see #13 for more information.

```
Could not parse input: UnparsedRemainder(startsWith=NOT@11 for "NOT" at 10 (1:11))
com.github.h0tk3y.betterParse.parser.ParseException: Could not parse input: UnparsedRemainder(startsWith=NOT@11 for "NOT" at 10 (1:11))
	at com.github.h0tk3y.betterParse.parser.ParserKt.toParsedOrThrow(Parser.kt:92)
	at com.github.h0tk3y.betterParse.parser.ParserKt.parseToEnd(Parser.kt:29)
	at com.github.h0tk3y.betterParse.grammar.GrammarKt.parseToEnd(Grammar.kt:70)
	at com.johnowl.rules.RulesEngine.check(RulesEngine.kt:11)
	at com.johnowl.rules.RulesEngineTest.validate all test cases from file(RulesEngineTest.kt:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by johnowl** [comment]
To work properly we should declare the token `NOT CONTAINS` before `NOT`.
